name: fatiando-data-southern-africa-topography
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9
  - pip
  - numpy
  - jupyterlab
  - xarray
  - netcdf4
  # PyGMT for plotting
  - pygmt==0.4.1
  - gmt==6.2.0
  # Fatiando
  - pooch>=1.0
